site_name: Panomix
repo_url: https://github.com/panomix/panomix/
repo_name: panomix/panomix
strict: true
nav:
  - index.md
  - Flagship - ADK : flagship/adk.md
  - 클라이언트 프로젝트 Client Cases:
      - 스웬 Swen: clients/news/swen.md
      - 소셜봇 SocialBot: clients/socialbot/socialbot.md
      - 뉴스챗 NewsChat: clients/newschat/newschat.md
      - 반도체 Semiconductor AI Project: clients/factory/factory.md
# English version
- English Home: en/index.md
- Flagship - ADK: en/flagship.md

  - 파트너십 Partnerships:
      - TikTok Marketing Partner: partners/tiktok/overview.md
      - Botpress Certified Partner: partners/botpress/overview.md

  - Our Framework: consulting/framework.md
  # - Consulting:
  #     - Discover: consulting/discover.md
  #     - Deliver: consulting/deliver.md

  # - In-house Products:
  #     - ATTN: products/attn.md
  # - Playbook:
  #     - Overview: playbook/overview.md
  #     - Features: playbook/features.md
  # - Swen AI:
  #     - Overview: swen/overview.md
  #     - Features: swen/features.md
  # - SocialBot:
  #     - Overview: socialbot/overview.md
  #     - Features: socialbot/features.md
  #     - Client Cases: socialbot/clientcases.md
  # - NewsChat:
  #     - Overview: newschat/overview.md
  #     - Features: newschat/features.md
  #     - Client Cases: newschat/clientcases.md
  # - Custom Apps:
  #     - Overview: custom/overview.md
  #     - Client Cases: custom/clientcases.md
  # - TikTok Marketing Partner:
  #     - Overview: tiktok/overview.md
  # - Botpress Certified Partner:
  #     - Overview: botpress/overview.md

theme:
  name: material
  custom_dir: docs/theme
  logo: assets/whitelogo.png
  favicon: assets/favicon.ico
  font:
    text: Inter

  palette:
      scheme: mesop-dark
      toggle:
        icon: material/brightness-7
        name: Switch to light mode 

  features:
    - content.code.copy
    - navigation.path
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.prune
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - search.highlight
  language: en

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - md_in_html

plugins:
  - blog
  - search
  - mkdocstrings:
      default_handler: python

      handlers:
        python:
          options:
            docstring_options:
              ignore_init_summary: true
            docstring_section_style: spacy
            heading_level: 3
            inherited_members: true
            merge_init_into_class: true
            separate_signature: false
            show_signature: false
            show_root_heading: true
            show_root_full_path: false
            show_source: false
            show_signature_annotations: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            signature_crossrefs: true
            summary: true
# extra:
#   alternate:
#     - name: English
#       link: /en/
#       lang: en
#     - name: 한국어
#       link: /ko/
#       lang: ko
